package com.tianfang.business.pojo;

import java.util.Date;

public class Addresses {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_addresses.id
     *
     * @mbggenerated Fri Mar 04 10:16:21 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_addresses.parent_id
     *
     * @mbggenerated Fri Mar 04 10:16:21 CST 2016
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_addresses.name
     *
     * @mbggenerated Fri Mar 04 10:16:21 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_addresses.level
     *
     * @mbggenerated Fri Mar 04 10:16:21 CST 2016
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_addresses.create_time
     *
     * @mbggenerated Fri Mar 04 10:16:21 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_addresses.last_update_time
     *
     * @mbggenerated Fri Mar 04 10:16:21 CST 2016
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_addresses.stat
     *
     * @mbggenerated Fri Mar 04 10:16:21 CST 2016
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_addresses.id
     *
     * @return the value of sst_addresses.id
     *
     * @mbggenerated Fri Mar 04 10:16:21 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_addresses.id
     *
     * @param id the value for sst_addresses.id
     *
     * @mbggenerated Fri Mar 04 10:16:21 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_addresses.parent_id
     *
     * @return the value of sst_addresses.parent_id
     *
     * @mbggenerated Fri Mar 04 10:16:21 CST 2016
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_addresses.parent_id
     *
     * @param parentId the value for sst_addresses.parent_id
     *
     * @mbggenerated Fri Mar 04 10:16:21 CST 2016
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_addresses.name
     *
     * @return the value of sst_addresses.name
     *
     * @mbggenerated Fri Mar 04 10:16:21 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_addresses.name
     *
     * @param name the value for sst_addresses.name
     *
     * @mbggenerated Fri Mar 04 10:16:21 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_addresses.level
     *
     * @return the value of sst_addresses.level
     *
     * @mbggenerated Fri Mar 04 10:16:21 CST 2016
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_addresses.level
     *
     * @param level the value for sst_addresses.level
     *
     * @mbggenerated Fri Mar 04 10:16:21 CST 2016
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_addresses.create_time
     *
     * @return the value of sst_addresses.create_time
     *
     * @mbggenerated Fri Mar 04 10:16:21 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_addresses.create_time
     *
     * @param createTime the value for sst_addresses.create_time
     *
     * @mbggenerated Fri Mar 04 10:16:21 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_addresses.last_update_time
     *
     * @return the value of sst_addresses.last_update_time
     *
     * @mbggenerated Fri Mar 04 10:16:21 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_addresses.last_update_time
     *
     * @param lastUpdateTime the value for sst_addresses.last_update_time
     *
     * @mbggenerated Fri Mar 04 10:16:21 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_addresses.stat
     *
     * @return the value of sst_addresses.stat
     *
     * @mbggenerated Fri Mar 04 10:16:21 CST 2016
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_addresses.stat
     *
     * @param stat the value for sst_addresses.stat
     *
     * @mbggenerated Fri Mar 04 10:16:21 CST 2016
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}