package com.tianfang.business.pojo;

import java.util.Date;

public class AlbumPicture {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_album_picture.id
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_album_picture.menu_type
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    private String menuType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_album_picture.album_id
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    private String albumId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_album_picture.pic
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_album_picture.shadow_pic
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    private String shadowPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_album_picture.title
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_album_picture.en_title
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    private String enTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_album_picture.described
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    private String described;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_album_picture.en_describe
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    private String enDescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_album_picture.last_update_time
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_album_picture.create_time
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_album_picture.stat
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    private Integer stat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_album_picture.team_id
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    private String teamId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_album_picture.user_id
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_album_picture.pic_status
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    private Integer picStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_album_picture.pic_type
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    private Integer picType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_album_picture.id
     *
     * @return the value of sst_album_picture.id
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_album_picture.id
     *
     * @param id the value for sst_album_picture.id
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_album_picture.menu_type
     *
     * @return the value of sst_album_picture.menu_type
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    public String getMenuType() {
        return menuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_album_picture.menu_type
     *
     * @param menuType the value for sst_album_picture.menu_type
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    public void setMenuType(String menuType) {
        this.menuType = menuType == null ? null : menuType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_album_picture.album_id
     *
     * @return the value of sst_album_picture.album_id
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    public String getAlbumId() {
        return albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_album_picture.album_id
     *
     * @param albumId the value for sst_album_picture.album_id
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    public void setAlbumId(String albumId) {
        this.albumId = albumId == null ? null : albumId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_album_picture.pic
     *
     * @return the value of sst_album_picture.pic
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_album_picture.pic
     *
     * @param pic the value for sst_album_picture.pic
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_album_picture.shadow_pic
     *
     * @return the value of sst_album_picture.shadow_pic
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    public String getShadowPic() {
        return shadowPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_album_picture.shadow_pic
     *
     * @param shadowPic the value for sst_album_picture.shadow_pic
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    public void setShadowPic(String shadowPic) {
        this.shadowPic = shadowPic == null ? null : shadowPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_album_picture.title
     *
     * @return the value of sst_album_picture.title
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_album_picture.title
     *
     * @param title the value for sst_album_picture.title
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_album_picture.en_title
     *
     * @return the value of sst_album_picture.en_title
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    public String getEnTitle() {
        return enTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_album_picture.en_title
     *
     * @param enTitle the value for sst_album_picture.en_title
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    public void setEnTitle(String enTitle) {
        this.enTitle = enTitle == null ? null : enTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_album_picture.described
     *
     * @return the value of sst_album_picture.described
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    public String getDescribed() {
        return described;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_album_picture.described
     *
     * @param described the value for sst_album_picture.described
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    public void setDescribed(String described) {
        this.described = described == null ? null : described.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_album_picture.en_describe
     *
     * @return the value of sst_album_picture.en_describe
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    public String getEnDescribe() {
        return enDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_album_picture.en_describe
     *
     * @param enDescribe the value for sst_album_picture.en_describe
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    public void setEnDescribe(String enDescribe) {
        this.enDescribe = enDescribe == null ? null : enDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_album_picture.last_update_time
     *
     * @return the value of sst_album_picture.last_update_time
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_album_picture.last_update_time
     *
     * @param lastUpdateTime the value for sst_album_picture.last_update_time
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_album_picture.create_time
     *
     * @return the value of sst_album_picture.create_time
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_album_picture.create_time
     *
     * @param createTime the value for sst_album_picture.create_time
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_album_picture.stat
     *
     * @return the value of sst_album_picture.stat
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_album_picture.stat
     *
     * @param stat the value for sst_album_picture.stat
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_album_picture.team_id
     *
     * @return the value of sst_album_picture.team_id
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    public String getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_album_picture.team_id
     *
     * @param teamId the value for sst_album_picture.team_id
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    public void setTeamId(String teamId) {
        this.teamId = teamId == null ? null : teamId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_album_picture.user_id
     *
     * @return the value of sst_album_picture.user_id
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_album_picture.user_id
     *
     * @param userId the value for sst_album_picture.user_id
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_album_picture.pic_status
     *
     * @return the value of sst_album_picture.pic_status
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    public Integer getPicStatus() {
        return picStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_album_picture.pic_status
     *
     * @param picStatus the value for sst_album_picture.pic_status
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    public void setPicStatus(Integer picStatus) {
        this.picStatus = picStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_album_picture.pic_type
     *
     * @return the value of sst_album_picture.pic_type
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    public Integer getPicType() {
        return picType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_album_picture.pic_type
     *
     * @param picType the value for sst_album_picture.pic_type
     *
     * @mbggenerated Fri Apr 01 10:35:14 CST 2016
     */
    public void setPicType(Integer picType) {
        this.picType = picType;
    }
}