package com.tianfang.business.pojo;

import java.util.Date;

public class Album {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_album.id
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_album.title
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_album.described
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    private String described;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_album.thumbnail
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    private String thumbnail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_album.publisher
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    private String publisher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_album.page_ranking
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    private Integer pageRanking;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_album.last_update_time
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_album.create_time
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_album.stat
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    private Integer stat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_album.team_id
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    private String teamId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_album.game_id
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    private String gameId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_album.pic_count
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    private Integer picCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_album.pic_type
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    private Integer picType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_album.id
     *
     * @return the value of sst_album.id
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_album.id
     *
     * @param id the value for sst_album.id
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_album.title
     *
     * @return the value of sst_album.title
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_album.title
     *
     * @param title the value for sst_album.title
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_album.described
     *
     * @return the value of sst_album.described
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    public String getDescribed() {
        return described;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_album.described
     *
     * @param described the value for sst_album.described
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    public void setDescribed(String described) {
        this.described = described == null ? null : described.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_album.thumbnail
     *
     * @return the value of sst_album.thumbnail
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    public String getThumbnail() {
        return thumbnail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_album.thumbnail
     *
     * @param thumbnail the value for sst_album.thumbnail
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    public void setThumbnail(String thumbnail) {
        this.thumbnail = thumbnail == null ? null : thumbnail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_album.publisher
     *
     * @return the value of sst_album.publisher
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_album.publisher
     *
     * @param publisher the value for sst_album.publisher
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    public void setPublisher(String publisher) {
        this.publisher = publisher == null ? null : publisher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_album.page_ranking
     *
     * @return the value of sst_album.page_ranking
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    public Integer getPageRanking() {
        return pageRanking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_album.page_ranking
     *
     * @param pageRanking the value for sst_album.page_ranking
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    public void setPageRanking(Integer pageRanking) {
        this.pageRanking = pageRanking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_album.last_update_time
     *
     * @return the value of sst_album.last_update_time
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_album.last_update_time
     *
     * @param lastUpdateTime the value for sst_album.last_update_time
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_album.create_time
     *
     * @return the value of sst_album.create_time
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_album.create_time
     *
     * @param createTime the value for sst_album.create_time
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_album.stat
     *
     * @return the value of sst_album.stat
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_album.stat
     *
     * @param stat the value for sst_album.stat
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_album.team_id
     *
     * @return the value of sst_album.team_id
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    public String getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_album.team_id
     *
     * @param teamId the value for sst_album.team_id
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    public void setTeamId(String teamId) {
        this.teamId = teamId == null ? null : teamId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_album.game_id
     *
     * @return the value of sst_album.game_id
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    public String getGameId() {
        return gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_album.game_id
     *
     * @param gameId the value for sst_album.game_id
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    public void setGameId(String gameId) {
        this.gameId = gameId == null ? null : gameId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_album.pic_count
     *
     * @return the value of sst_album.pic_count
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    public Integer getPicCount() {
        return picCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_album.pic_count
     *
     * @param picCount the value for sst_album.pic_count
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    public void setPicCount(Integer picCount) {
        this.picCount = picCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_album.pic_type
     *
     * @return the value of sst_album.pic_type
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    public Integer getPicType() {
        return picType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_album.pic_type
     *
     * @param picType the value for sst_album.pic_type
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    public void setPicType(Integer picType) {
        this.picType = picType;
    }
}