package com.tianfang.message.pojo;

import java.util.Date;

public class Notice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_notice.id
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_notice.title
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_notice.create_user_id
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_notice.create_user_name
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    private String createUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_notice.content
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_notice.update_user_id
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_notice.update_user_name
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    private String updateUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_notice.group_id
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_notice.group_name
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_notice.pic
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_notice.create_time
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_notice.last_update_time
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_notice.stat
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    private Integer stat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_notice.read_stat
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    private Integer readStat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_notice.allow_forward
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    private Integer allowForward;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_notice.id
     *
     * @return the value of sst_notice.id
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_notice.id
     *
     * @param id the value for sst_notice.id
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_notice.title
     *
     * @return the value of sst_notice.title
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_notice.title
     *
     * @param title the value for sst_notice.title
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_notice.create_user_id
     *
     * @return the value of sst_notice.create_user_id
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_notice.create_user_id
     *
     * @param createUserId the value for sst_notice.create_user_id
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_notice.create_user_name
     *
     * @return the value of sst_notice.create_user_name
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_notice.create_user_name
     *
     * @param createUserName the value for sst_notice.create_user_name
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName == null ? null : createUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_notice.content
     *
     * @return the value of sst_notice.content
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_notice.content
     *
     * @param content the value for sst_notice.content
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_notice.update_user_id
     *
     * @return the value of sst_notice.update_user_id
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_notice.update_user_id
     *
     * @param updateUserId the value for sst_notice.update_user_id
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_notice.update_user_name
     *
     * @return the value of sst_notice.update_user_name
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    public String getUpdateUserName() {
        return updateUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_notice.update_user_name
     *
     * @param updateUserName the value for sst_notice.update_user_name
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    public void setUpdateUserName(String updateUserName) {
        this.updateUserName = updateUserName == null ? null : updateUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_notice.group_id
     *
     * @return the value of sst_notice.group_id
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_notice.group_id
     *
     * @param groupId the value for sst_notice.group_id
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_notice.group_name
     *
     * @return the value of sst_notice.group_name
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_notice.group_name
     *
     * @param groupName the value for sst_notice.group_name
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_notice.pic
     *
     * @return the value of sst_notice.pic
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_notice.pic
     *
     * @param pic the value for sst_notice.pic
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_notice.create_time
     *
     * @return the value of sst_notice.create_time
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_notice.create_time
     *
     * @param createTime the value for sst_notice.create_time
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_notice.last_update_time
     *
     * @return the value of sst_notice.last_update_time
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_notice.last_update_time
     *
     * @param lastUpdateTime the value for sst_notice.last_update_time
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_notice.stat
     *
     * @return the value of sst_notice.stat
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_notice.stat
     *
     * @param stat the value for sst_notice.stat
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_notice.read_stat
     *
     * @return the value of sst_notice.read_stat
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    public Integer getReadStat() {
        return readStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_notice.read_stat
     *
     * @param readStat the value for sst_notice.read_stat
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    public void setReadStat(Integer readStat) {
        this.readStat = readStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_notice.allow_forward
     *
     * @return the value of sst_notice.allow_forward
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    public Integer getAllowForward() {
        return allowForward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_notice.allow_forward
     *
     * @param allowForward the value for sst_notice.allow_forward
     *
     * @mbggenerated Mon Mar 28 18:07:39 CST 2016
     */
    public void setAllowForward(Integer allowForward) {
        this.allowForward = allowForward;
    }
}