package com.tianfang.user.pojo;

import java.util.Date;

public class Memo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_memo.id
     *
     * @mbggenerated Fri Jan 15 15:56:31 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_memo.content
     *
     * @mbggenerated Fri Jan 15 15:56:31 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_memo.user_id
     *
     * @mbggenerated Fri Jan 15 15:56:31 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_memo.user_name
     *
     * @mbggenerated Fri Jan 15 15:56:31 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_memo.create_time
     *
     * @mbggenerated Fri Jan 15 15:56:31 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_memo.last_update_time
     *
     * @mbggenerated Fri Jan 15 15:56:31 CST 2016
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_memo.stat
     *
     * @mbggenerated Fri Jan 15 15:56:31 CST 2016
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_memo.id
     *
     * @return the value of sst_memo.id
     *
     * @mbggenerated Fri Jan 15 15:56:31 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_memo.id
     *
     * @param id the value for sst_memo.id
     *
     * @mbggenerated Fri Jan 15 15:56:31 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_memo.content
     *
     * @return the value of sst_memo.content
     *
     * @mbggenerated Fri Jan 15 15:56:31 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_memo.content
     *
     * @param content the value for sst_memo.content
     *
     * @mbggenerated Fri Jan 15 15:56:31 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_memo.user_id
     *
     * @return the value of sst_memo.user_id
     *
     * @mbggenerated Fri Jan 15 15:56:31 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_memo.user_id
     *
     * @param userId the value for sst_memo.user_id
     *
     * @mbggenerated Fri Jan 15 15:56:31 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_memo.user_name
     *
     * @return the value of sst_memo.user_name
     *
     * @mbggenerated Fri Jan 15 15:56:31 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_memo.user_name
     *
     * @param userName the value for sst_memo.user_name
     *
     * @mbggenerated Fri Jan 15 15:56:31 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_memo.create_time
     *
     * @return the value of sst_memo.create_time
     *
     * @mbggenerated Fri Jan 15 15:56:31 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_memo.create_time
     *
     * @param createTime the value for sst_memo.create_time
     *
     * @mbggenerated Fri Jan 15 15:56:31 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_memo.last_update_time
     *
     * @return the value of sst_memo.last_update_time
     *
     * @mbggenerated Fri Jan 15 15:56:31 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_memo.last_update_time
     *
     * @param lastUpdateTime the value for sst_memo.last_update_time
     *
     * @mbggenerated Fri Jan 15 15:56:31 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_memo.stat
     *
     * @return the value of sst_memo.stat
     *
     * @mbggenerated Fri Jan 15 15:56:31 CST 2016
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_memo.stat
     *
     * @param stat the value for sst_memo.stat
     *
     * @mbggenerated Fri Jan 15 15:56:31 CST 2016
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}