package com.tianfang.user.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class NotificationsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sport_notifications
     *
     * @mbggenerated Wed Mar 16 09:30:12 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sport_notifications
     *
     * @mbggenerated Wed Mar 16 09:30:12 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sport_notifications
     *
     * @mbggenerated Wed Mar 16 09:30:12 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_notifications
     *
     * @mbggenerated Wed Mar 16 09:30:12 CST 2016
     */
    public NotificationsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_notifications
     *
     * @mbggenerated Wed Mar 16 09:30:12 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_notifications
     *
     * @mbggenerated Wed Mar 16 09:30:12 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_notifications
     *
     * @mbggenerated Wed Mar 16 09:30:12 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_notifications
     *
     * @mbggenerated Wed Mar 16 09:30:12 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_notifications
     *
     * @mbggenerated Wed Mar 16 09:30:12 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_notifications
     *
     * @mbggenerated Wed Mar 16 09:30:12 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_notifications
     *
     * @mbggenerated Wed Mar 16 09:30:12 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_notifications
     *
     * @mbggenerated Wed Mar 16 09:30:12 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_notifications
     *
     * @mbggenerated Wed Mar 16 09:30:12 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_notifications
     *
     * @mbggenerated Wed Mar 16 09:30:12 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sport_notifications
     *
     * @mbggenerated Wed Mar 16 09:30:12 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUpPasswordStatIsNull() {
            addCriterion("up_password_stat is null");
            return (Criteria) this;
        }

        public Criteria andUpPasswordStatIsNotNull() {
            addCriterion("up_password_stat is not null");
            return (Criteria) this;
        }

        public Criteria andUpPasswordStatEqualTo(Integer value) {
            addCriterion("up_password_stat =", value, "upPasswordStat");
            return (Criteria) this;
        }

        public Criteria andUpPasswordStatNotEqualTo(Integer value) {
            addCriterion("up_password_stat <>", value, "upPasswordStat");
            return (Criteria) this;
        }

        public Criteria andUpPasswordStatGreaterThan(Integer value) {
            addCriterion("up_password_stat >", value, "upPasswordStat");
            return (Criteria) this;
        }

        public Criteria andUpPasswordStatGreaterThanOrEqualTo(Integer value) {
            addCriterion("up_password_stat >=", value, "upPasswordStat");
            return (Criteria) this;
        }

        public Criteria andUpPasswordStatLessThan(Integer value) {
            addCriterion("up_password_stat <", value, "upPasswordStat");
            return (Criteria) this;
        }

        public Criteria andUpPasswordStatLessThanOrEqualTo(Integer value) {
            addCriterion("up_password_stat <=", value, "upPasswordStat");
            return (Criteria) this;
        }

        public Criteria andUpPasswordStatIn(List<Integer> values) {
            addCriterion("up_password_stat in", values, "upPasswordStat");
            return (Criteria) this;
        }

        public Criteria andUpPasswordStatNotIn(List<Integer> values) {
            addCriterion("up_password_stat not in", values, "upPasswordStat");
            return (Criteria) this;
        }

        public Criteria andUpPasswordStatBetween(Integer value1, Integer value2) {
            addCriterion("up_password_stat between", value1, value2, "upPasswordStat");
            return (Criteria) this;
        }

        public Criteria andUpPasswordStatNotBetween(Integer value1, Integer value2) {
            addCriterion("up_password_stat not between", value1, value2, "upPasswordStat");
            return (Criteria) this;
        }

        public Criteria andLoginStatIsNull() {
            addCriterion("login_stat is null");
            return (Criteria) this;
        }

        public Criteria andLoginStatIsNotNull() {
            addCriterion("login_stat is not null");
            return (Criteria) this;
        }

        public Criteria andLoginStatEqualTo(Integer value) {
            addCriterion("login_stat =", value, "loginStat");
            return (Criteria) this;
        }

        public Criteria andLoginStatNotEqualTo(Integer value) {
            addCriterion("login_stat <>", value, "loginStat");
            return (Criteria) this;
        }

        public Criteria andLoginStatGreaterThan(Integer value) {
            addCriterion("login_stat >", value, "loginStat");
            return (Criteria) this;
        }

        public Criteria andLoginStatGreaterThanOrEqualTo(Integer value) {
            addCriterion("login_stat >=", value, "loginStat");
            return (Criteria) this;
        }

        public Criteria andLoginStatLessThan(Integer value) {
            addCriterion("login_stat <", value, "loginStat");
            return (Criteria) this;
        }

        public Criteria andLoginStatLessThanOrEqualTo(Integer value) {
            addCriterion("login_stat <=", value, "loginStat");
            return (Criteria) this;
        }

        public Criteria andLoginStatIn(List<Integer> values) {
            addCriterion("login_stat in", values, "loginStat");
            return (Criteria) this;
        }

        public Criteria andLoginStatNotIn(List<Integer> values) {
            addCriterion("login_stat not in", values, "loginStat");
            return (Criteria) this;
        }

        public Criteria andLoginStatBetween(Integer value1, Integer value2) {
            addCriterion("login_stat between", value1, value2, "loginStat");
            return (Criteria) this;
        }

        public Criteria andLoginStatNotBetween(Integer value1, Integer value2) {
            addCriterion("login_stat not between", value1, value2, "loginStat");
            return (Criteria) this;
        }

        public Criteria andNonlocalLoginStatIsNull() {
            addCriterion("nonlocal_login_stat is null");
            return (Criteria) this;
        }

        public Criteria andNonlocalLoginStatIsNotNull() {
            addCriterion("nonlocal_login_stat is not null");
            return (Criteria) this;
        }

        public Criteria andNonlocalLoginStatEqualTo(Integer value) {
            addCriterion("nonlocal_login_stat =", value, "nonlocalLoginStat");
            return (Criteria) this;
        }

        public Criteria andNonlocalLoginStatNotEqualTo(Integer value) {
            addCriterion("nonlocal_login_stat <>", value, "nonlocalLoginStat");
            return (Criteria) this;
        }

        public Criteria andNonlocalLoginStatGreaterThan(Integer value) {
            addCriterion("nonlocal_login_stat >", value, "nonlocalLoginStat");
            return (Criteria) this;
        }

        public Criteria andNonlocalLoginStatGreaterThanOrEqualTo(Integer value) {
            addCriterion("nonlocal_login_stat >=", value, "nonlocalLoginStat");
            return (Criteria) this;
        }

        public Criteria andNonlocalLoginStatLessThan(Integer value) {
            addCriterion("nonlocal_login_stat <", value, "nonlocalLoginStat");
            return (Criteria) this;
        }

        public Criteria andNonlocalLoginStatLessThanOrEqualTo(Integer value) {
            addCriterion("nonlocal_login_stat <=", value, "nonlocalLoginStat");
            return (Criteria) this;
        }

        public Criteria andNonlocalLoginStatIn(List<Integer> values) {
            addCriterion("nonlocal_login_stat in", values, "nonlocalLoginStat");
            return (Criteria) this;
        }

        public Criteria andNonlocalLoginStatNotIn(List<Integer> values) {
            addCriterion("nonlocal_login_stat not in", values, "nonlocalLoginStat");
            return (Criteria) this;
        }

        public Criteria andNonlocalLoginStatBetween(Integer value1, Integer value2) {
            addCriterion("nonlocal_login_stat between", value1, value2, "nonlocalLoginStat");
            return (Criteria) this;
        }

        public Criteria andNonlocalLoginStatNotBetween(Integer value1, Integer value2) {
            addCriterion("nonlocal_login_stat not between", value1, value2, "nonlocalLoginStat");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNull() {
            addCriterion("last_update_time is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNotNull() {
            addCriterion("last_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeEqualTo(Date value) {
            addCriterion("last_update_time =", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotEqualTo(Date value) {
            addCriterion("last_update_time <>", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThan(Date value) {
            addCriterion("last_update_time >", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_update_time >=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThan(Date value) {
            addCriterion("last_update_time <", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_update_time <=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIn(List<Date> values) {
            addCriterion("last_update_time in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotIn(List<Date> values) {
            addCriterion("last_update_time not in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("last_update_time between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_update_time not between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andStatIsNull() {
            addCriterion("stat is null");
            return (Criteria) this;
        }

        public Criteria andStatIsNotNull() {
            addCriterion("stat is not null");
            return (Criteria) this;
        }

        public Criteria andStatEqualTo(Integer value) {
            addCriterion("stat =", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatNotEqualTo(Integer value) {
            addCriterion("stat <>", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatGreaterThan(Integer value) {
            addCriterion("stat >", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatGreaterThanOrEqualTo(Integer value) {
            addCriterion("stat >=", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatLessThan(Integer value) {
            addCriterion("stat <", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatLessThanOrEqualTo(Integer value) {
            addCriterion("stat <=", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatIn(List<Integer> values) {
            addCriterion("stat in", values, "stat");
            return (Criteria) this;
        }

        public Criteria andStatNotIn(List<Integer> values) {
            addCriterion("stat not in", values, "stat");
            return (Criteria) this;
        }

        public Criteria andStatBetween(Integer value1, Integer value2) {
            addCriterion("stat between", value1, value2, "stat");
            return (Criteria) this;
        }

        public Criteria andStatNotBetween(Integer value1, Integer value2) {
            addCriterion("stat not between", value1, value2, "stat");
            return (Criteria) this;
        }

        public Criteria andOwnerIdIsNull() {
            addCriterion("owner_id is null");
            return (Criteria) this;
        }

        public Criteria andOwnerIdIsNotNull() {
            addCriterion("owner_id is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerIdEqualTo(String value) {
            addCriterion("owner_id =", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdNotEqualTo(String value) {
            addCriterion("owner_id <>", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdGreaterThan(String value) {
            addCriterion("owner_id >", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdGreaterThanOrEqualTo(String value) {
            addCriterion("owner_id >=", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdLessThan(String value) {
            addCriterion("owner_id <", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdLessThanOrEqualTo(String value) {
            addCriterion("owner_id <=", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdLike(String value) {
            addCriterion("owner_id like", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdNotLike(String value) {
            addCriterion("owner_id not like", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdIn(List<String> values) {
            addCriterion("owner_id in", values, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdNotIn(List<String> values) {
            addCriterion("owner_id not in", values, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdBetween(String value1, String value2) {
            addCriterion("owner_id between", value1, value2, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdNotBetween(String value1, String value2) {
            addCriterion("owner_id not between", value1, value2, "ownerId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sport_notifications
     *
     * @mbggenerated do_not_delete_during_merge Wed Mar 16 09:30:12 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sport_notifications
     *
     * @mbggenerated Wed Mar 16 09:30:12 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}