package com.tianfang.user.pojo;

import java.util.Date;

public class Remind {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_remind.id
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_remind.to_user_id
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    private String toUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_remind.to_user_name
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    private String toUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_remind.type
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_remind.send_time
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    private Date sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_remind.attachment
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    private String attachment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_remind.text
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_remind.voice
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    private String voice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_remind.user_id
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_remind.user_name
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_remind.create_time
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_remind.last_update_time
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_remind.stat
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_remind.id
     *
     * @return the value of sst_remind.id
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_remind.id
     *
     * @param id the value for sst_remind.id
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_remind.to_user_id
     *
     * @return the value of sst_remind.to_user_id
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    public String getToUserId() {
        return toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_remind.to_user_id
     *
     * @param toUserId the value for sst_remind.to_user_id
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    public void setToUserId(String toUserId) {
        this.toUserId = toUserId == null ? null : toUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_remind.to_user_name
     *
     * @return the value of sst_remind.to_user_name
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    public String getToUserName() {
        return toUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_remind.to_user_name
     *
     * @param toUserName the value for sst_remind.to_user_name
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    public void setToUserName(String toUserName) {
        this.toUserName = toUserName == null ? null : toUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_remind.type
     *
     * @return the value of sst_remind.type
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_remind.type
     *
     * @param type the value for sst_remind.type
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_remind.send_time
     *
     * @return the value of sst_remind.send_time
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_remind.send_time
     *
     * @param sendTime the value for sst_remind.send_time
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_remind.attachment
     *
     * @return the value of sst_remind.attachment
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    public String getAttachment() {
        return attachment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_remind.attachment
     *
     * @param attachment the value for sst_remind.attachment
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    public void setAttachment(String attachment) {
        this.attachment = attachment == null ? null : attachment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_remind.text
     *
     * @return the value of sst_remind.text
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_remind.text
     *
     * @param text the value for sst_remind.text
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_remind.voice
     *
     * @return the value of sst_remind.voice
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    public String getVoice() {
        return voice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_remind.voice
     *
     * @param voice the value for sst_remind.voice
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    public void setVoice(String voice) {
        this.voice = voice == null ? null : voice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_remind.user_id
     *
     * @return the value of sst_remind.user_id
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_remind.user_id
     *
     * @param userId the value for sst_remind.user_id
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_remind.user_name
     *
     * @return the value of sst_remind.user_name
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_remind.user_name
     *
     * @param userName the value for sst_remind.user_name
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_remind.create_time
     *
     * @return the value of sst_remind.create_time
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_remind.create_time
     *
     * @param createTime the value for sst_remind.create_time
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_remind.last_update_time
     *
     * @return the value of sst_remind.last_update_time
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_remind.last_update_time
     *
     * @param lastUpdateTime the value for sst_remind.last_update_time
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_remind.stat
     *
     * @return the value of sst_remind.stat
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_remind.stat
     *
     * @param stat the value for sst_remind.stat
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}