package com.tianfang.business.mapper;

import com.tianfang.business.pojo.Album;
import com.tianfang.business.pojo.AlbumExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AlbumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_album
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    int countByExample(AlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_album
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    int deleteByExample(AlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_album
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_album
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    int insert(Album record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_album
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    int insertSelective(Album record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_album
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    List<Album> selectByExample(AlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_album
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    Album selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_album
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    int updateByExampleSelective(@Param("record") Album record, @Param("example") AlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_album
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    int updateByExample(@Param("record") Album record, @Param("example") AlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_album
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    int updateByPrimaryKeySelective(Album record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_album
     *
     * @mbggenerated Mon Feb 29 10:36:37 CST 2016
     */
    int updateByPrimaryKey(Album record);
}