package com.tianfang.message.mapper;

import com.tianfang.message.pojo.Message;
import com.tianfang.message.pojo.MessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_message
     *
     * @mbggenerated Mon Jan 11 16:22:06 CST 2016
     */
    int countByExample(MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_message
     *
     * @mbggenerated Mon Jan 11 16:22:06 CST 2016
     */
    int deleteByExample(MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_message
     *
     * @mbggenerated Mon Jan 11 16:22:06 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_message
     *
     * @mbggenerated Mon Jan 11 16:22:06 CST 2016
     */
    int insert(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_message
     *
     * @mbggenerated Mon Jan 11 16:22:06 CST 2016
     */
    int insertSelective(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_message
     *
     * @mbggenerated Mon Jan 11 16:22:06 CST 2016
     */
    List<Message> selectByExample(MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_message
     *
     * @mbggenerated Mon Jan 11 16:22:06 CST 2016
     */
    Message selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_message
     *
     * @mbggenerated Mon Jan 11 16:22:06 CST 2016
     */
    int updateByExampleSelective(@Param("record") Message record, @Param("example") MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_message
     *
     * @mbggenerated Mon Jan 11 16:22:06 CST 2016
     */
    int updateByExample(@Param("record") Message record, @Param("example") MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_message
     *
     * @mbggenerated Mon Jan 11 16:22:06 CST 2016
     */
    int updateByPrimaryKeySelective(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_message
     *
     * @mbggenerated Mon Jan 11 16:22:06 CST 2016
     */
    int updateByPrimaryKey(Message record);
}