package com.tianfang.admin.pojo;

import java.util.Date;

public class Authorization {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_authorization.id
     *
     * @mbggenerated Mon Jan 11 17:19:08 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_authorization.admin_id
     *
     * @mbggenerated Mon Jan 11 17:19:08 CST 2016
     */
    private String adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_authorization.menu_id
     *
     * @mbggenerated Mon Jan 11 17:19:08 CST 2016
     */
    private String menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_authorization.create_time
     *
     * @mbggenerated Mon Jan 11 17:19:08 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_authorization.stat
     *
     * @mbggenerated Mon Jan 11 17:19:08 CST 2016
     */
    private Integer stat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_authorization.last_update_time
     *
     * @mbggenerated Mon Jan 11 17:19:08 CST 2016
     */
    private Date lastUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_authorization.id
     *
     * @return the value of sst_authorization.id
     *
     * @mbggenerated Mon Jan 11 17:19:08 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_authorization.id
     *
     * @param id the value for sst_authorization.id
     *
     * @mbggenerated Mon Jan 11 17:19:08 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_authorization.admin_id
     *
     * @return the value of sst_authorization.admin_id
     *
     * @mbggenerated Mon Jan 11 17:19:08 CST 2016
     */
    public String getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_authorization.admin_id
     *
     * @param adminId the value for sst_authorization.admin_id
     *
     * @mbggenerated Mon Jan 11 17:19:08 CST 2016
     */
    public void setAdminId(String adminId) {
        this.adminId = adminId == null ? null : adminId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_authorization.menu_id
     *
     * @return the value of sst_authorization.menu_id
     *
     * @mbggenerated Mon Jan 11 17:19:08 CST 2016
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_authorization.menu_id
     *
     * @param menuId the value for sst_authorization.menu_id
     *
     * @mbggenerated Mon Jan 11 17:19:08 CST 2016
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null ? null : menuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_authorization.create_time
     *
     * @return the value of sst_authorization.create_time
     *
     * @mbggenerated Mon Jan 11 17:19:08 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_authorization.create_time
     *
     * @param createTime the value for sst_authorization.create_time
     *
     * @mbggenerated Mon Jan 11 17:19:08 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_authorization.stat
     *
     * @return the value of sst_authorization.stat
     *
     * @mbggenerated Mon Jan 11 17:19:08 CST 2016
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_authorization.stat
     *
     * @param stat the value for sst_authorization.stat
     *
     * @mbggenerated Mon Jan 11 17:19:08 CST 2016
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_authorization.last_update_time
     *
     * @return the value of sst_authorization.last_update_time
     *
     * @mbggenerated Mon Jan 11 17:19:08 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_authorization.last_update_time
     *
     * @param lastUpdateTime the value for sst_authorization.last_update_time
     *
     * @mbggenerated Mon Jan 11 17:19:08 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }
}