package com.tianfang.user.mapper;

import com.tianfang.user.pojo.Group;
import com.tianfang.user.pojo.GroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_group
     *
     * @mbggenerated Fri Jan 15 13:21:40 CST 2016
     */
    int countByExample(GroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_group
     *
     * @mbggenerated Fri Jan 15 13:21:40 CST 2016
     */
    int deleteByExample(GroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_group
     *
     * @mbggenerated Fri Jan 15 13:21:40 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_group
     *
     * @mbggenerated Fri Jan 15 13:21:40 CST 2016
     */
    int insert(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_group
     *
     * @mbggenerated Fri Jan 15 13:21:40 CST 2016
     */
    int insertSelective(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_group
     *
     * @mbggenerated Fri Jan 15 13:21:40 CST 2016
     */
    List<Group> selectByExample(GroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_group
     *
     * @mbggenerated Fri Jan 15 13:21:40 CST 2016
     */
    Group selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_group
     *
     * @mbggenerated Fri Jan 15 13:21:40 CST 2016
     */
    int updateByExampleSelective(@Param("record") Group record, @Param("example") GroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_group
     *
     * @mbggenerated Fri Jan 15 13:21:40 CST 2016
     */
    int updateByExample(@Param("record") Group record, @Param("example") GroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_group
     *
     * @mbggenerated Fri Jan 15 13:21:40 CST 2016
     */
    int updateByPrimaryKeySelective(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_group
     *
     * @mbggenerated Fri Jan 15 13:21:40 CST 2016
     */
    int updateByPrimaryKey(Group record);
}