package com.tianfang.user.mapper;

import com.tianfang.user.pojo.GroupUser;
import com.tianfang.user.pojo.GroupUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GroupUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_group_user
     *
     * @mbggenerated Mon Jan 11 16:19:40 CST 2016
     */
    int countByExample(GroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_group_user
     *
     * @mbggenerated Mon Jan 11 16:19:40 CST 2016
     */
    int deleteByExample(GroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_group_user
     *
     * @mbggenerated Mon Jan 11 16:19:40 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_group_user
     *
     * @mbggenerated Mon Jan 11 16:19:40 CST 2016
     */
    int insert(GroupUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_group_user
     *
     * @mbggenerated Mon Jan 11 16:19:40 CST 2016
     */
    int insertSelective(GroupUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_group_user
     *
     * @mbggenerated Mon Jan 11 16:19:40 CST 2016
     */
    List<GroupUser> selectByExample(GroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_group_user
     *
     * @mbggenerated Mon Jan 11 16:19:40 CST 2016
     */
    GroupUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_group_user
     *
     * @mbggenerated Mon Jan 11 16:19:40 CST 2016
     */
    int updateByExampleSelective(@Param("record") GroupUser record, @Param("example") GroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_group_user
     *
     * @mbggenerated Mon Jan 11 16:19:40 CST 2016
     */
    int updateByExample(@Param("record") GroupUser record, @Param("example") GroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_group_user
     *
     * @mbggenerated Mon Jan 11 16:19:40 CST 2016
     */
    int updateByPrimaryKeySelective(GroupUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_group_user
     *
     * @mbggenerated Mon Jan 11 16:19:40 CST 2016
     */
    int updateByPrimaryKey(GroupUser record);
}