package com.tianfang.user.mapper;

import com.tianfang.user.pojo.Remind;
import com.tianfang.user.pojo.RemindExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RemindMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_remind
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    int countByExample(RemindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_remind
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    int deleteByExample(RemindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_remind
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_remind
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    int insert(Remind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_remind
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    int insertSelective(Remind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_remind
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    List<Remind> selectByExample(RemindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_remind
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    Remind selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_remind
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    int updateByExampleSelective(@Param("record") Remind record, @Param("example") RemindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_remind
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    int updateByExample(@Param("record") Remind record, @Param("example") RemindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_remind
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    int updateByPrimaryKeySelective(Remind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_remind
     *
     * @mbggenerated Fri Jan 15 17:01:04 CST 2016
     */
    int updateByPrimaryKey(Remind record);
}