package com.tianfang.user.mapper;

import com.tianfang.user.pojo.User;
import com.tianfang.user.pojo.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_user
     *
     * @mbggenerated Tue Mar 08 11:28:17 CST 2016
     */
    int countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_user
     *
     * @mbggenerated Tue Mar 08 11:28:17 CST 2016
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_user
     *
     * @mbggenerated Tue Mar 08 11:28:17 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_user
     *
     * @mbggenerated Tue Mar 08 11:28:17 CST 2016
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_user
     *
     * @mbggenerated Tue Mar 08 11:28:17 CST 2016
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_user
     *
     * @mbggenerated Tue Mar 08 11:28:17 CST 2016
     */
    List<User> selectByExampleWithBLOBs(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_user
     *
     * @mbggenerated Tue Mar 08 11:28:17 CST 2016
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_user
     *
     * @mbggenerated Tue Mar 08 11:28:17 CST 2016
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_user
     *
     * @mbggenerated Tue Mar 08 11:28:17 CST 2016
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_user
     *
     * @mbggenerated Tue Mar 08 11:28:17 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_user
     *
     * @mbggenerated Tue Mar 08 11:28:17 CST 2016
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_user
     *
     * @mbggenerated Tue Mar 08 11:28:17 CST 2016
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_user
     *
     * @mbggenerated Tue Mar 08 11:28:17 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_user
     *
     * @mbggenerated Tue Mar 08 11:28:17 CST 2016
     */
    int updateByPrimaryKey(User record);
}