package com.tianfang.user.mapper;

import com.tianfang.user.pojo.UserFriend;
import com.tianfang.user.pojo.UserFriendExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserFriendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_user_friend
     *
     * @mbggenerated Mon Mar 07 13:27:31 CST 2016
     */
    int countByExample(UserFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_user_friend
     *
     * @mbggenerated Mon Mar 07 13:27:31 CST 2016
     */
    int deleteByExample(UserFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_user_friend
     *
     * @mbggenerated Mon Mar 07 13:27:31 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_user_friend
     *
     * @mbggenerated Mon Mar 07 13:27:31 CST 2016
     */
    int insert(UserFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_user_friend
     *
     * @mbggenerated Mon Mar 07 13:27:31 CST 2016
     */
    int insertSelective(UserFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_user_friend
     *
     * @mbggenerated Mon Mar 07 13:27:31 CST 2016
     */
    List<UserFriend> selectByExample(UserFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_user_friend
     *
     * @mbggenerated Mon Mar 07 13:27:31 CST 2016
     */
    UserFriend selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_user_friend
     *
     * @mbggenerated Mon Mar 07 13:27:31 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserFriend record, @Param("example") UserFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_user_friend
     *
     * @mbggenerated Mon Mar 07 13:27:31 CST 2016
     */
    int updateByExample(@Param("record") UserFriend record, @Param("example") UserFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_user_friend
     *
     * @mbggenerated Mon Mar 07 13:27:31 CST 2016
     */
    int updateByPrimaryKeySelective(UserFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_user_friend
     *
     * @mbggenerated Mon Mar 07 13:27:31 CST 2016
     */
    int updateByPrimaryKey(UserFriend record);
}