package com.tianfang.user.mapper;

import com.tianfang.user.pojo.VoteUserTemp;
import com.tianfang.user.pojo.VoteUserTempExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VoteUserTempMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_vote_user_temp
     *
     * @mbggenerated Tue Mar 08 16:36:45 CST 2016
     */
    int countByExample(VoteUserTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_vote_user_temp
     *
     * @mbggenerated Tue Mar 08 16:36:45 CST 2016
     */
    int deleteByExample(VoteUserTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_vote_user_temp
     *
     * @mbggenerated Tue Mar 08 16:36:45 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_vote_user_temp
     *
     * @mbggenerated Tue Mar 08 16:36:45 CST 2016
     */
    int insert(VoteUserTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_vote_user_temp
     *
     * @mbggenerated Tue Mar 08 16:36:45 CST 2016
     */
    int insertSelective(VoteUserTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_vote_user_temp
     *
     * @mbggenerated Tue Mar 08 16:36:45 CST 2016
     */
    List<VoteUserTemp> selectByExample(VoteUserTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_vote_user_temp
     *
     * @mbggenerated Tue Mar 08 16:36:45 CST 2016
     */
    VoteUserTemp selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_vote_user_temp
     *
     * @mbggenerated Tue Mar 08 16:36:45 CST 2016
     */
    int updateByExampleSelective(@Param("record") VoteUserTemp record, @Param("example") VoteUserTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_vote_user_temp
     *
     * @mbggenerated Tue Mar 08 16:36:45 CST 2016
     */
    int updateByExample(@Param("record") VoteUserTemp record, @Param("example") VoteUserTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_vote_user_temp
     *
     * @mbggenerated Tue Mar 08 16:36:45 CST 2016
     */
    int updateByPrimaryKeySelective(VoteUserTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_vote_user_temp
     *
     * @mbggenerated Tue Mar 08 16:36:45 CST 2016
     */
    int updateByPrimaryKey(VoteUserTemp record);
}