package com.tianfang.admin.mapper;

import com.tianfang.admin.pojo.Banner;
import com.tianfang.admin.pojo.BannerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BannerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_banner
     *
     * @mbggenerated Fri Feb 26 10:42:04 CST 2016
     */
    int countByExample(BannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_banner
     *
     * @mbggenerated Fri Feb 26 10:42:04 CST 2016
     */
    int deleteByExample(BannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_banner
     *
     * @mbggenerated Fri Feb 26 10:42:04 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_banner
     *
     * @mbggenerated Fri Feb 26 10:42:04 CST 2016
     */
    int insert(Banner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_banner
     *
     * @mbggenerated Fri Feb 26 10:42:04 CST 2016
     */
    int insertSelective(Banner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_banner
     *
     * @mbggenerated Fri Feb 26 10:42:04 CST 2016
     */
    List<Banner> selectByExample(BannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_banner
     *
     * @mbggenerated Fri Feb 26 10:42:04 CST 2016
     */
    Banner selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_banner
     *
     * @mbggenerated Fri Feb 26 10:42:04 CST 2016
     */
    int updateByExampleSelective(@Param("record") Banner record, @Param("example") BannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_banner
     *
     * @mbggenerated Fri Feb 26 10:42:04 CST 2016
     */
    int updateByExample(@Param("record") Banner record, @Param("example") BannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_banner
     *
     * @mbggenerated Fri Feb 26 10:42:04 CST 2016
     */
    int updateByPrimaryKeySelective(Banner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_banner
     *
     * @mbggenerated Fri Feb 26 10:42:04 CST 2016
     */
    int updateByPrimaryKey(Banner record);
}