package com.tianfang.admin.mapper;

import com.tianfang.admin.pojo.HomeMenu;
import com.tianfang.admin.pojo.HomeMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HomeMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_home_menu
     *
     * @mbggenerated Wed Mar 16 15:56:39 CST 2016
     */
    int countByExample(HomeMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_home_menu
     *
     * @mbggenerated Wed Mar 16 15:56:39 CST 2016
     */
    int deleteByExample(HomeMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_home_menu
     *
     * @mbggenerated Wed Mar 16 15:56:39 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_home_menu
     *
     * @mbggenerated Wed Mar 16 15:56:39 CST 2016
     */
    int insert(HomeMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_home_menu
     *
     * @mbggenerated Wed Mar 16 15:56:39 CST 2016
     */
    int insertSelective(HomeMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_home_menu
     *
     * @mbggenerated Wed Mar 16 15:56:39 CST 2016
     */
    List<HomeMenu> selectByExampleWithBLOBs(HomeMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_home_menu
     *
     * @mbggenerated Wed Mar 16 15:56:39 CST 2016
     */
    List<HomeMenu> selectByExample(HomeMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_home_menu
     *
     * @mbggenerated Wed Mar 16 15:56:39 CST 2016
     */
    HomeMenu selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_home_menu
     *
     * @mbggenerated Wed Mar 16 15:56:39 CST 2016
     */
    int updateByExampleSelective(@Param("record") HomeMenu record, @Param("example") HomeMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_home_menu
     *
     * @mbggenerated Wed Mar 16 15:56:39 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") HomeMenu record, @Param("example") HomeMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_home_menu
     *
     * @mbggenerated Wed Mar 16 15:56:39 CST 2016
     */
    int updateByExample(@Param("record") HomeMenu record, @Param("example") HomeMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_home_menu
     *
     * @mbggenerated Wed Mar 16 15:56:39 CST 2016
     */
    int updateByPrimaryKeySelective(HomeMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_home_menu
     *
     * @mbggenerated Wed Mar 16 15:56:39 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(HomeMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_home_menu
     *
     * @mbggenerated Wed Mar 16 15:56:39 CST 2016
     */
    int updateByPrimaryKey(HomeMenu record);
}